### PR TITLE
Add cel5 symbol to cosmetic and other small changes

### PR DESCRIPTION
**Pull request by Hirame1**
* Added cel 5 symbol to celestial glyph cosmetic set
* Reduced multiplier entry blinking speed
* Removed multiplier entry flashing effect on touch (this only happens on a PC with touch panel)
* Widen android perk layout to make it look nicer
* Reword change log entry to make it clear
image

### CODE REVIEW

**Comment by Hirame1** [comment]
image

**Review by cyip92 — COMMENTED** [review]
I'm not sure if it's a browser-dependent thing nor if it's even fixable, but the new cel5 icon isn't vertically centered for me on Chrome+Win11:
image
(Although with the infinity glyph symbol already being weird for some people's setups, that might be fine to just ignore.)

The rest of the changes look good; I don't have a device to test the touchscreen-specific change, but I trust you on that 👍

**Comment by Hirame1** [comment]
I'm on Chrome124 + Win11, and I don't see the glyph icon offset issue :blobsad:

And about the multiplier tab flashing issue, please refer to the screen recording for your reference.

https://github.com/IvarK/AntimatterDimensionsSourceCode/assets/56225774/9f0e7449-af0d-48be-bad0-02a607857b60

**Review by cyip92 — APPROVED** [review]
Looks good to me for a merge then :blobhugcat:

**Pull request merged**
